openapi: 3.0.0
info:
  description: API for COMP30220 Group Project. 
  version: "1.0.0"
  title: DistributedImagination
externalDocs:
  description: GitLab Repository
  url: https://gitlab.com/distributed_imagination/comp30040-assignment-2
  
tags:
  - name: clients
    description: Endpoints available to the client (provided by internal services)
  - name: postal_services
    description: Endpoints (internal) provided by each postal service

paths:
  /quotations:
    put:
      tags:
        - clients
      summary: request quotations
      description: Request a list of quotations for the supplied package specifications
      requestBody:
        description: Specification of package
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
      responses:
        '200':
          description: quotations for package order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quotation'
        '400':
          description: invalid input
          
  /quote:
    put:
      tags:
        - postal_services
      summary: request quotation
      description: Request quotation for the supplied package specifications
      requestBody:
        description: Specification of package
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
      responses:
        '200':
          description: quotations for package order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quotation'
        '400':
          description: invalid input
          
  /deliver/{providerId}:
    post:
      tags:
        - clients
      summary: place order/start delivery
      description: Request to place delivery order to specified provider
      parameters:
        - name: providerId
          in: path
          description: ID of postal provider
          required: true
          example: 'dhl'
          schema:
            type: string
      requestBody:
        description: Specification of package
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
      responses:
        '200':
          description: confirmation of order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrackingInfo'
        '400':
          description: invalid input
        '404':
          description: provider not found
          
  /deliver:
    post:
      tags:
        - postal_services
      summary: place order/start delivery
      description: Request to place delivery order to specified provider
      requestBody:
        description: Specification of package
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
      responses:
        '200':
          description: confirmation of order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrackingInfo'
        '400':
          description: invalid input
        '404':
          description: provider not found
          
  /track/{trackingId}:
    get:
      tags:
        - clients
      summary: request tracking information
      description: Request tracking information for specified trackingId
      parameters:
        - name: trackingId
          in: path
          description: tracking id or number
          required: true
          example: 'DHL-001'
          schema:
            type: string
      responses:
        '200':
          description: confirmation of order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrackingInfo'
        '400':
          description: invalid input
        '404':
          description: unknown trackingId
    
  /info/{trackingId}:
    get:
      tags:
        - postal_services
      summary: request tracking information
      description: Request tracking information for specified trackingId
      parameters:
        - name: trackingId
          in: path
          description: tracking id or number
          required: true
          example: 'DHL-001'
          schema:
            type: string
      responses:
        '200':
          description: order information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrackingInfo'
        '400':
          description: invalid input
        '404':
          description: unknown trackingId
          

components:
  schemas:
    Application:
      type: object
      required:
        - weight
        - length
        - width
        - height
        - destination
      properties:
        weight:
          type: integer
          format: gram
          example: 200
          description: weight of package in grams
        length:
          type: integer
          format: cm
          example: 30
          description: length of package in cm
        width:
          type: integer
          format: cm
          example: 20
          description: height of package in cm
        height:
          type: integer
          format: cm
          example: 10
          description: height of package in cm
        destination:
          type: string
          format: country code
          example: 'ie'
          description: country code of destination

    Quotation:
      type: object
      required:
        - cost
        - time
        - provider
      properties:
        cost:
          type: number
          format: currency
          example: 3.87
          description: estimated cost of sending the package
        time:
          type: integer
          format: days
          example: 7
          description: estimated time needed for delivery in days
        provider:
          $ref: '#/components/schemas/Provider'
          
    TrackingInfo:
      type: object
      required:
        - id
        - status
        - eta
        - provider
      properties:
        id:
          type: string
          example: 'dhl-001'
          description: tracking number/id
        status:
          type: string
          enum: ['Order confirmed', 'At sorting center', 'Out for delivery', 'Delivered']
        eta:
          type: string
          format: date
          example: '2020-11-24'
          description: estimated delivery date
        provider:
          $ref: '#/components/schemas/Provider'
          
    Provider:
      type: object
      required:
        - name
        - id
      properties:
        name:
          type: string
          example: 'DHL'
        id:
          type: string
          example: 'dhl'
        website:
          type: string
          format: url
          example: 'https://www.dhl.com/'
        phone:
          type: string
          example: '0818725725'