openapi: 3.0.0
info:
  description: API for COMP30220 Group Project. 
  version: "1.0.0"
  title: DistributedImagination
externalDocs:
  description: GitLab Repository
  url: https://gitlab.com/distributed_imagination/comp30040-assignment-2
  
tags:
  - name: clients
    description: Endpoints available to the client (provided by Zuul)
  - name: postal_services
    description: Endpoints (internal) provided by each postal service

paths:
  /quotations:
    post:
      tags:
        - clients
      summary: request quotations
      description: Request a list of quotations for the supplied package specifications
      requestBody:
        description: Specification of package
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: quotations for package order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          description: invalid input
          
  /quote:
    post:
      tags:
        - postal_services
      summary: request quotation
      description: Request quotation for the supplied package specifications
      requestBody:
        description: Specification of package
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: quotations for package order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: invalid input
          
  /deliver/{providerId}:
    post:
      tags:
        - clients
      summary: place order/start delivery
      description: Request to place delivery order to specified provider
      parameters:
        - name: providerId
          in: path
          description: ID of postal provider
          required: true
          example: 'dhl'
          schema:
            type: string
      requestBody:
        description: Specification of package
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: confirmation of order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          description: invalid input
        '404':
          description: provider not found
          
  /orders:
    post:
      tags:
        - postal_services
      summary: place order/start delivery
      description: Request to place delivery order to specified provider
      requestBody:
        description: Specification of package
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: confirmation of order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          description: invalid input
        '404':
          description: provider not found
          
  /track/{trackingId}:
    get:
      tags:
        - clients
      summary: request tracking information
      description: Request tracking information for specified trackingId
      parameters:
        - name: trackingId
          in: path
          description: tracking id or number
          required: true
          example: '8dc92c0a-ef52-4cb9-8060-e2979847175c'
          schema:
            type: string
      responses:
        '200':
          description: confirmation of order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          description: invalid input
        '404':
          description: unknown trackingId
    
  /orders/{orderId}:
    get:
      tags:
        - postal_services
      summary: request tracking information
      description: Request tracking information for specified trackingId
      parameters:
        - name: orderId
          in: path
          description: order oid
          required: true
          example: '8dc92c0a-ef52-4cb9-8060-e2979847175c'
          schema:
            type: string
      responses:
        '200':
          description: order information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          description: invalid input
        '404':
          description: unknown trackingId
          

components:
  schemas:
    Order:
      type: object
      required:
        - sourceLon
        - sourceLat
        - destinationLon
        - destinationLat
        - parcels
      properties:
        oid:
          type: string
          format: uuid
          example: "8dc92c0a-ef52-4cb9-8060-e2979847175c"
          description: oid of order, generated by server
        sourceLon:
          type: number
          format: longitude
          example: 53.349804
          description: longitude of source location
        sourceLat:
          type: number
          format: latitude
          example: -6.260310
          description: latitude of source location
        destinationLon:
          type: number
          format: longitude
          example: 53.349804
          description: longitude of destination location
        destinationLat:
          type: number
          format: latitude
          example: -6.260310
          description: latitude of destination location
        locationLon:
          type: number
          format: longitude
          example: 53.349804
          description: longitude of current location, filled in by server
        locationLat:
          type: number
          format: latitude
          example: -6.260310
          description: latitude of current location, filled in by server
        cost:
          type: number
          format: currency
          example: 3.03
          description: cost of order, generated by server
        dateOrder:
          type: string
          format: date
          example: "2020-12-23T17:04:40.052+00:00"
          description: date when order was placed, generated by server
        dateDelivery:
          type: string
          format: date
          example: "2020-12-23T17:04:40.052+00:00"
          description: date of expected delivery, generated by server
        parcels:
          type: array
          items:
            $ref: '#/components/schemas/Parcel'
    
    Parcel:
      type: object
      required:
        - weightKg
        - lengthCm
        - widthCm
        - heightCm
      properties:
        oid:
          type: string
          format: uuid
          example: "8dc92c0a-ef52-4cb9-8060-e2979847175c"
          description: oid of parcel, generated by server
        weightKg:
          type: integer
          format: gram
          example: 200
          description: weight of package in grams
        lengthCm:
          type: integer
          format: cm
          example: 30
          description: length of package in cm
        widthCm:
          type: integer
          format: cm
          example: 20
          description: height of package in cm
        heightCm:
          type: integer
          format: cm
          example: 10
          description: height of package in cm