version: '3'
services:
  # discovery-main:
  #   image: distributed_imagination/discovery:0.0.1-SNAPSHOT     Single Discovery System
  #   ports:
  #     - 8761:8761

  discovery:
    build:
      dockerfile: Dockerfile
      context: discovery
    image: distributed_imagination/discovery:0.0.1
    environment:
      - JAVA_OPTS=
        -Dspring.profiles.active=peer-1
        -DEUREKA_URI=http://discovery-peer:9002/eureka
    ports:
      - 8761:8761

  discovery-peer:
    image: distributed_imagination/discovery:0.0.1
    environment:
      - JAVA_OPTS=
        -Dspring.profiles.active=peer-2
        -DEUREKA_URI=http://discovery:8761/eureka
    ports:
      - 9002:9002

  router:
    build:
      dockerfile: Dockerfile
      context: router
    image: distributed_imagination/router:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_URI1=http://discovery:8761/eureka
        -DEUREKA_URI2=http://discovery-peer:9002/eureka
    depends_on:
      - discovery
      - discovery-peer
    ports:
      - 8762:8762

  postal-service:
    build:
      dockerfile: Dockerfile
      context: postal-service
    image: distributed_imagination/postal-service:0.0.1
    environment:
      - JAVA_OPTS=
        -DEUREKA_URI1=http://discovery:8761/eureka
        -DEUREKA_URI2=http://discovery-peer:9002/eureka
        -Dspring.profiles.active=local
        -DCOST_MULTIPLIER=0.69
        -DSIMULATION_INTERVAL=5000
        -DDELIVERY_SPEED=10000
        -DPOSTAL_SERVICE_NAME=DHL
        -DPOSTAL_SERVICE_ID=dhl
        -DPORT=8408
        -DDATASOURCE_URI=jdbc:postgresql://database:5432/
    depends_on:
      - discovery
      - discovery-peer
      - database
    ports:
      - 8408:8408

  postal-service-2:
     build:
       dockerfile: Dockerfile
       context: postal-service
     image: distributed_imagination/postal-service:0.0.1
     environment:
       - JAVA_OPTS=
         -DEUREKA_URI1=http://discovery:8761/eureka
         -DEUREKA_URI2=http://discovery-peer:9002/eureka
         -Dspring.profiles.active=local
         -DCOST_MULTIPLIER=0.80
         -DSIMULATION_INTERVAL=5000
         -DDELIVERY_SPEED=10000
         -DPOSTAL_SERVICE_NAME=ANPOST
         -DPOSTAL_SERVICE_ID=anp
         -DDATASOURCE_URI=jdbc:postgresql://database-2:5432/
         -DPORT=8409
     depends_on:
       - discovery
       - discovery-peer
       - database-2
     ports:
       - 8409:8408

  postal-service-3:
     build:
       dockerfile: Dockerfile
       context: postal-service
     image: distributed_imagination/postal-service:0.0.1
     environment:
       - JAVA_OPTS=
         -DEUREKA_URI1=http://discovery:8761/eureka
         -DEUREKA_URI2=http://discovery-peer:9002/eureka
         -Dspring.profiles.active=local
         -DCOST_MULTIPLIER=0.4
         -DSIMULATION_INTERVAL=5000
         -DDELIVERY_SPEED=10000
         -DPOSTAL_SERVICE_NAME=FASTWAY
         -DPOSTAL_SERVICE_ID=fwy
         -DDATASOURCE_URI=jdbc:postgresql://database-3:5432/
         -DPORT=8410
     depends_on:
       - discovery
       - discovery-peer
       - database-3
     ports:
       - 8410:8408

  database:
    image: "postgres" 
    env_file:
      - database.env 
    ports: 
      - 5432:5432

  database-2:
     image: "postgres" 
     env_file:
       - database.env 
     ports:
       - 5433:5432

  database-3:
     image: "postgres" 
     env_file:
       - database.env 
     ports:
       - 5434:5432


  quotations:
     build:
       dockerfile: Dockerfile
       context: quotations
     image: distributed_imagination/quotationservice:0.0.1-SNAPSHOT
     environment:
       - JAVA_OPTS=
         -DEUREKA_URI1=http://discovery:8761/eureka
         -DEUREKA_URI2=http://discovery-peer:9002/eureka
     depends_on:
       - discovery
       - discovery-peer
       - postal-service
     ports:
       - 8800:8800

  delivery:
    build:
      dockerfile: Dockerfile
      context: delivery
    image: distributed_imagination/delivery:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_URI1=http://discovery:8761/eureka
        -DEUREKA_URI2=http://discovery-peer:9002/eureka
    depends_on:
      - discovery
      - discovery-peer
      - postal-service
    ports:
      - 8802:8802

  tracking:
    build:
      dockerfile: Dockerfile
      context: tracking
    image: distributed_imagination/tracking:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_URI1=http://discovery:8761/eureka
        -DEUREKA_URI2=http://discovery-peer:9002/eureka
    depends_on:
      - discovery
      - discovery-peer
      - postal-service
    ports:
      - 8801:8801

  client:
    build:
      dockerfile: Dockerfile
      context: client
    image: distributed_imagination/client
    ports:
      - 80:80