version: '3'
services:
  discovery:
    image: distributed_imagination/discovery:0.0.1-SNAPSHOT
    ports:
      - 8761:8761

  router:
    image: distributed_imagination/router:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
    ports:
      - 8762:8762