apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: discovery
  name: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discovery
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: discovery
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: ' -Dspring.profiles.active=peer-1 -DEUREKA_URI=http://discovery-peer:9002/eureka'
        image: registry.gitlab.com/distributed_imagination/comp30040-assignment-2/discovery:0.0.1
        imagePullPolicy: ""
        name: discovery
        ports:
        - containerPort: 8761
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
      imagePullSecrets:
        - name: regcred
status: {}
