apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: postal-service-2
  name: postal-service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postal-service-2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: postal-service-2
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: ' -DEUREKA_URI1=http://discovery:8761/eureka -DEUREKA_URI2=http://discovery-peer:9002/eureka
            -Dspring.profiles.active=local -DCOST_MULTIPLIER=0.80 -DSIMULATION_INTERVAL=5000
            -DDELIVERY_SPEED=10000 -DPOSTAL_SERVICE_NAME=ANPOST -DPOSTAL_SERVICE_ID=anp
            -DDATASOURCE_URI=jdbc:postgresql://database-2:5432/ -DPORT=8409'
        image: registry.gitlab.com/distributed_imagination/comp30040-assignment-2/postal-service:0.0.1
        imagePullPolicy: ""
        name: postal-service-2
        ports:
        - containerPort: 8408
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
      imagePullSecrets:
        - name: regcred
status: {}
