image: maven:latest


stages:
  - build_application
  - publish_image


build_application:
  stage: build_application
  script:
    - cd postal-service
    - mvn package -Dmaven.test.skip=true -U
  artifacts:
    #IMPORTANT: Path is relative from the root of the project!
    paths:
      - postal-service/target


publish_image:
  image: docker:latest
  services:
    - docker:dind
  stage: publish_image
  script:
    - projectPath=registry.gitlab.com/distributed_imagination/comp30040-assignment-2
    - version=$(grep 'version=' postal-service/target/maven-archiver/pom.properties | grep -oE '(=).*(.=?.)' | cut -d'=' -f 2)
    - artifact=$(grep 'artifactId=' postal-service/target/maven-archiver/pom.properties | grep -oE '(=).*(.=?.)' | cut -d'=' -f 2)
    - echo $artifact
    - echo $version
    - cd $artifact
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build --no-cache=true -t $projectPath/$artifact:$version .
    - docker push $projectPath/$artifact:$version
  only:
    - master
